In [22]:
import numpy as np
import sklearn as sk

In [23]:
sk??

Type:        module
String form: <module 'sklearn' from '/home/tushar/miniconda3/envs/horizon25/lib/python3.12/site-packages/sklearn/__init__.py'>
File:        ~/miniconda3/envs/horizon25/lib/python3.12/site-packages/sklearn/__init__.py
Source:     
"""Configure global settings and get information about the working environment."""

# Authors: The scikit-learn developers
# SPDX-License-Identifier: BSD-3-Clause

# Machine learning module for Python
# ==================================
#
# sklearn is a Python module integrating classical machine
# learning algorithms in the tightly-knit world of scientific Python
# packages (numpy, scipy, matplotlib).
#
# It aims to provide simple and efficient solutions to learning problems
# that are accessible to everybody and reusable in various contexts:
# machine-learning as a versatile tool for science and engineering.
#
# See https://scikit-learn.org for complete documentation.

import importlib as _importlib
import logging
import os
import random

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
model = LinearRegression()
model

LinearRegression()

In [26]:
x_simple = np.array([1,2,3,4,5]).reshape(-1, 1) # Hours
y_simple = np.array([55,60,75,70,85])  # Scores

x_simple, y_simple

(array([[1],
        [2],
        [3],
        [4],
        [5]]),
 array([55, 60, 75, 70, 85]))

In [27]:
model.fit(x_simple, y_simple)

LinearRegression()

In [28]:
y_pred = model.predict(x_simple)
y_pred

array([55., 62., 69., 76., 83.])

In [29]:
from sklearn.metrics import mean_squared_error, r2_score

In [30]:
mse = mean_squared_error(y_simple, y_pred)
mse

16.0

In [31]:
r2 = r2_score(Y_simple, y_pred)
r2

0.8596491228070176

In [33]:
model.predict([[8],[3],[4],[12]])

array([104.,  69.,  76., 132.])