In [1]:
import numpy as np
# The make_blobs function is used to generate synthetic datasets for clustering.
from sklearn.datasets import make_blobs

In [2]:
# Checking the documentation for the make_blobs module in sklearn using "??"
make_blobs??



Signature:
make_blobs(
    n_samples=100,
    n_features=2,
    *,
    centers=None,
    cluster_std=1.0,
    center_box=(-10.0, 10.0),
    shuffle=True,
    random_state=None,
    return_centers=False,
)
Source:   
@validate_params(
    {
        "n_samples": [Interval(Integral, 1, None, closed="left"), "array-like"],
        "n_features": [Interval(Integral, 1, None, closed="left")],
        "centers": [Interval(Integral, 1, None, closed="left"), "array-like", None],
        "cluster_std": [Interval(Real, 0, None, closed="left"), "array-like"],
        "center_box": [tuple],
        "shuffle": ["boolean"],
        "random_state": ["random_state"],
        "return_centers": ["boolean"],
    },
    prefer_skip_nested_validation=True,
)
def make_blobs(
    n_samples=100,
    n_features=2,
    *,
    centers=None,
    cluster_std=1.0,
    center_box=(-10.0, 10.0),
    shuffle=True,
    random_state=None,
    return_centers=False,
):
    """Generate isotropic Gaussian blobs for clustering

In [3]:
X_blobs, y_blobs_true = make_blobs(n_samples=100, centers=3)
# We created a dataset with 100 samples and 3 centers.
# The shape of the dataset is (100, 2) indicating 100 samples with 2 features each.
print(f"Shape of the dataset: {X_blobs.shape}")
# The true labels for the dataset are stored in y_blobs_true.
# The shape of the true labels is (100,) indicating 100 samples with their corresponding labels.
print(f"Shape of the true labels: {y_blobs_true.shape}")
# The first 5 samples of the dataset
print(X_blobs[:5])
# The first 5 true labels
print(y_blobs_true[:5])

Shape of the dataset: (100, 2)
Shape of the true labels: (100,)
[[-7.89103028  0.66614939]
 [ 0.48859637  6.50288819]
 [ 2.95643446  7.51274205]
 [-8.95904239  0.73214769]
 [ 5.93701467  5.39770259]]
[2 1 1 2 0]


In [4]:
import sklearn as sk
# Checking the documentation for the cluster module in sklearn using "??"
sk.cluster??
# We have many clustering algorithms available in sklearn. 
# We will use KMeans.

Type:        module
String form: <module 'sklearn.cluster' from '/home/tushar/miniconda3/envs/horizon25/lib/python3.12/site-packages/sklearn/cluster/__init__.py'>
File:        ~/miniconda3/envs/horizon25/lib/python3.12/site-packages/sklearn/cluster/__init__.py
Source:     
"""Popular unsupervised clustering algorithms."""

# Authors: The scikit-learn developers
# SPDX-License-Identifier: BSD-3-Clause

from ._affinity_propagation import AffinityPropagation, affinity_propagation
from ._agglomerative import (
    AgglomerativeClustering,
    FeatureAgglomeration,
    linkage_tree,
    ward_tree,
)
from ._bicluster import SpectralBiclustering, SpectralCoclustering
from ._birch import Birch
from ._bisect_k_means import BisectingKMeans
from ._dbscan import DBSCAN, dbscan
from ._hdbscan.hdbscan import HDBSCAN
from ._kmeans import KMeans, MiniBatchKMeans, k_means, kmeans_plusplus
from ._mean_shift import MeanShift, estimate_bandwidth, get_bin_seeds, mean_shift
from ._optics import (
    OPTICS

In [5]:
# Importing the KMeans class from sklearn.cluster.
from sklearn.cluster import KMeans

In [6]:
# We created an instance of the KMeans class with 3 clusters.
km = KMeans(n_clusters=3)
km

KMeans(n_clusters=3)

In [7]:
# Let us fit the KMeans model to our dataset.
km.fit(X_blobs)

KMeans(n_clusters=3)

In [8]:
# Let us examine the cluster centers.
centers = km.cluster_centers_
print(f"Cluster centers:\n{centers}")

Cluster centers:
[[ 2.88144459  6.37390145]
 [-8.06832997 -0.51375547]
 [ 5.92303794  5.23173771]]


In [9]:
# The labels assigned to each sample in the dataset.
labels = km.labels_
# These labels indicate which cluster each sample belongs to.
# The shape of the labels is (100,) indicating 100 samples with their corresponding cluster labels.
print(f"Labels shape: {labels.shape}")
# The first 5 labels assigned to the samples.
print(f"First 5 labels: {labels[:5]}")

Labels shape: (100,)
First 5 labels: [1 0 0 1 2]
